#!/usr/bin/env python3
"""Deterministic test-only Kiwi oracle; no network, no MoonCassowary imports.

Requires Python 3.13.x, kiwisolver==1.4.9, and moonfmt from the MoonBit toolchain.
Run from any directory:
  python tests/oracle/generate.py          # explicitly regenerate fixtures
  python tests/oracle/generate.py --check # compare a temporary regeneration

192 scenarios with 2--5 variables, hard bounds, sparse affine constraints,
conflicting soft inequalities, fractional coefficients/weights, variable scales,
and add/remove/edit sequences. Every operation checks feasibility and the
weighted L1 objective. Underdetermined systems do NOT compare arbitrary values;
only fully pinned, mathematically unique systems additionally compare values.
Upstream: Nucleic/kiwi 728f5661fdd021c68dac1b914b3c8610a46b2e7e (1.4.9).
Kiwi is BSD-3-Clause; retained license: tests/oracle/LICENSE.kiwi.
"""
from __future__ import annotations

import argparse
import difflib
import math
from pathlib import Path
import random
import subprocess
import sys
import tempfile

import kiwisolver as kiwi

SEED = 0xC4550A
SCENARIOS = 192
REQUIRED = 1001001000.0
OUTPUT = Path(__file__).resolve().parents[2] / "oracle_test.mbt"


def number(value: float) -> str:
    value = float(value)
    if not math.isfinite(value):
        raise ValueError("fixtures must contain finite Doubles")
    if value == 0:
        return "0.0"
    text = repr(value)
    if "e" in text:
        mantissa, exponent = text.split("e")
        if "." not in mantissa:
            mantissa += ".0"
        return mantissa + "e" + exponent
    return text if "." in text else text + ".0"


def violation(row: tuple, values: list[float]) -> float:
    terms, constant, relation, _ = row
    residual = sum(coefficient * values[index] for index, coefficient in terms) + constant
    return abs(residual) if relation == 0 else max(0.0, residual if relation == 1 else -residual)


def verify_exact_errors() -> int:
    """Manually specified exception names, never inferred from this library."""
    solver = kiwi.Solver()
    x, y = kiwi.Variable("x"), kiwi.Variable("y")
    c, opposite = x >= 1.0, x <= 0.0
    solver.addConstraint(c)
    checks = [
        (lambda: solver.addConstraint(c), kiwi.DuplicateConstraint),
        (lambda: solver.removeConstraint(opposite), kiwi.UnknownConstraint),
        (lambda: solver.addConstraint(opposite), kiwi.UnsatisfiableConstraint),
        (lambda: solver.removeEditVariable(x), kiwi.UnknownEditVariable),
        (lambda: solver.suggestValue(x, 1.0), kiwi.UnknownEditVariable),
        (lambda: solver.addEditVariable(y, kiwi.strength.required), kiwi.BadRequiredStrength),
    ]
    solver.addEditVariable(x, kiwi.strength.weak)
    # The first unknown-edit checks must use an unregistered variable.
    checks[3] = (lambda: solver.removeEditVariable(y), kiwi.UnknownEditVariable)
    checks[4] = (lambda: solver.suggestValue(y, 1.0), kiwi.UnknownEditVariable)
    checks.append((lambda: solver.addEditVariable(x, kiwi.strength.medium), kiwi.DuplicateEditVariable))
    for operation, expected in checks:
        try:
            operation()
        except Exception as error:
            if type(error) is not expected:
                raise AssertionError(f"expected {expected.__name__}, got {type(error).__name__}") from error
        else:
            raise AssertionError(f"missing {expected.__name__}")
    return len(checks)


HELPERS = r'''// GENERATED by tests/oracle/generate.py; do not edit fixtures by hand.
// Test-only oracle: kiwisolver 1.4.9, BSD-3-Clause.
// Pinned upstream: 728f5661fdd021c68dac1b914b3c8610a46b2e7e.
// Seed: 0xC4550A. --check regenerates in a temporary directory, never updates.
// Raw residuals below intentionally do NOT call Expression.value or
// Constraint.violation: those would only test the implementation against itself.

///|
priv struct OracleRow {
  terms : Array[(Int, Double)]
  constant : Double
  relation : Int
  strength : Double
}

///|
fn oracle_abs(x : Double) -> Double {
  if x < 0.0 { -x } else { x }
}

///|
fn oracle_residual(row : OracleRow, values : Array[Double]) -> Double {
  let mut residual = row.constant
  for (index, coefficient) in row.terms {
    residual += coefficient * values[index]
  }
  match row.relation {
    0 => oracle_abs(residual)
    1 => if residual > 0.0 { residual } else { 0.0 }
    _ => if residual < 0.0 { -residual } else { 0.0 }
  }
}

///|
fn oracle_run(
  case_id : Int,
  count : Int,
  rows : Array[OracleRow],
  // op: 0 add, 1 remove, 2 add-edit, 3 suggest, 4 remove-edit.
  steps : Array[(Int, Int, Double)],
  // Every step: Kiwi feasible, required residual, weighted objective,
  // and values ONLY when all variables are pinned by required equalities.
  snapshots : Array[(Bool, Double, Double, Array[Double])],
) -> Unit raise {
  let solver = @cassowary.Solver::new()
  let variables = Array::makei(count, i => @cassowary.Variable::new("v\{i}"))
  let constraints = rows.map(row => {
    let terms = row.terms.map(term => (variables[term.0], term.1))
    let relation = match row.relation {
      0 => @cassowary.Relation::Equal
      1 => @cassowary.Relation::LessEqual
      _ => @cassowary.Relation::GreaterEqual
    }
    @cassowary.Constraint::new(
      @cassowary.Expression::new(terms, constant=row.constant),
      relation,
      strength=row.strength,
    )
  })
  let active = Array::make(rows.length(), false)
  let edit_strength = Array::make(count, 0.0)
  let edit_target = Array::make(count, 0.0)
  assert_eq(steps.length(), snapshots.length())
  for step_index, step in steps {
    let (op, index, value) = step
    match op {
      0 => {
        solver.add_constraint(constraints[index])
        active[index] = true
      }
      1 => {
        solver.remove_constraint(constraints[index])
        active[index] = false
      }
      2 => {
        solver.add_edit_variable(variables[index], value)
        edit_strength[index] = value
        edit_target[index] = 0.0
      }
      3 => {
        solver.suggest_value(variables[index], value)
        edit_target[index] = value
      }
      _ => {
        solver.remove_edit_variable(variables[index])
        edit_strength[index] = 0.0
      }
    }
    let values = variables.map(v => solver.value(v))
    for value in values {
      // NaN and infinities fail even if a subsequent inequality would hide them.
      assert_true(value == value && oracle_abs(value) < 1.0e100)
    }
    let mut hard = 0.0
    let mut objective = 0.0
    for row_index, row in rows {
      assert_eq(solver.has_constraint(constraints[row_index]), active[row_index])
      if active[row_index] {
        let residual = oracle_residual(row, values)
        if row.strength == 1001001000.0 {
          if residual > hard { hard = residual }
        } else {
          objective += row.strength * residual
        }
      }
    }
    for i = 0; i < count; i = i + 1 {
      assert_eq(solver.has_edit_variable(variables[i]), edit_strength[i] > 0.0)
      objective += edit_strength[i] * oracle_abs(values[i] - edit_target[i])
    }
    let (feasible, expected_hard, expected_objective, unique_values) = snapshots[step_index]
    assert_true(feasible)
    assert_true(
      hard <= 1.0e-6 + expected_hard,
      msg="oracle case \{case_id} step \{step_index}: hard residual \{hard}",
    )
    assert_true(
      oracle_abs(objective - expected_objective) <= 1.0e-6 + 1.0e-8 * oracle_abs(expected_objective),
      msg="oracle case \{case_id} step \{step_index}: objective \{objective}, Kiwi \{expected_objective}",
    )
    if unique_values.length() > 0 {
      assert_eq(unique_values.length(), count)
      for i = 0; i < count; i = i + 1 {
        assert_true(oracle_abs(values[i] - unique_values[i]) <= 1.0e-6 * (1.0 + oracle_abs(unique_values[i])))
      }
    }
  }
}

'''


def make_case(case_id: int) -> tuple[str, int, int]:
    # One independent seed per case makes failures replayable without prior cases.
    rng = random.Random(SEED + case_id)
    count = 2 + case_id % 4
    scales = [rng.choice([0.125, 0.5, 1.0, 8.0, 32.0, 256.0]) for _ in range(count)]
    witness = [rng.randint(-24, 24) * 0.25 * scale for scale in scales]
    rows: list[tuple] = []
    steps: list[tuple] = []
    pins: set[int] = set()

    def row(terms, constant, relation, strength=REQUIRED):
        index = len(rows)
        rows.append((terms, constant, relation, strength))
        return index

    def add(index):
        steps.append((0, index, 0.0))

    for i in range(count):
        width = rng.uniform(1.0, 6.0) * scales[i]
        add(row([(i, 1.0)], -witness[i] + width, 2))
        add(row([(i, 1.0)], -witness[i] - width, 1))
    if case_id % 8 == 0:
        for i in range(count):
            index = row([(i, 1.0 / scales[i])], -witness[i] / scales[i], 0)
            pins.add(index)
            add(index)

    mutable_hard = []
    for j in range(3):
        indices = sorted(rng.sample(range(count), rng.randint(1, min(3, count))))
        terms = [(i, rng.choice([-2.0, -0.5, 0.25, 1.0, 4.0]) / scales[i]) for i in indices]
        at_witness = sum(c * witness[i] for i, c in terms)
        relation = j % 3
        slack = rng.uniform(0.5, 4.0)
        constant = -at_witness + (0.0 if relation == 0 else -slack if relation == 1 else slack)
        index = row(terms, constant, relation)
        mutable_hard.append(index)
        add(index)

    soft = []
    weights = [0.25, 1.0, 3.5, 10.0, 1000.0, 3500.0, 1000000.0]
    # Both are deliberately incompatible with the hard bounds and one another.
    for relation, target in [(1, witness[0] / scales[0] - 10.25), (2, witness[0] / scales[0] + 10.75)]:
        index = row([(0, 1.0 / scales[0])], -target, relation, rng.choice(weights))
        soft.append(index)
        add(index)
    for j in range(6):
        indices = sorted(rng.sample(range(count), rng.randint(1, min(3, count))))
        terms = [(i, rng.choice([-2.5, -1.0, -0.125, 0.25, 0.75, 3.0]) / scales[i]) for i in indices]
        if j == 0:  # Deliberate duplicate raw terms; independent checker keeps them.
            i, c = terms[0]
            terms[0:1] = [(i, c * 0.25), (i, c * 0.75)]
        index = row(terms, rng.uniform(-12.0, 12.0), rng.randrange(3), rng.choice(weights))
        soft.append(index)
        add(index)

    edit_a, edit_b = rng.sample(range(count), 2)
    steps.extend([(2, edit_a, 1000.0), (2, edit_b, 3.5)])
    for multiplier in [2.25, -3.5, 0.0, 1.125]:
        steps.extend([(3, edit_a, witness[edit_a] + multiplier * scales[edit_a]),
                      (3, edit_b, witness[edit_b] - multiplier * scales[edit_b])])
    removed_soft = rng.choice(soft)
    removed_hard = rng.choice(mutable_hard)
    steps.extend([(1, removed_soft, 0.0), (1, removed_hard, 0.0),
                  (3, edit_a, witness[edit_a] + 20.5 * scales[edit_a]),
                  (0, removed_soft, 0.0), (0, removed_hard, 0.0),
                  (4, edit_b, 0.0), (4, edit_a, 0.0),
                  (2, edit_a, 0.25), (3, edit_a, -2.75 * scales[edit_a]),
                  (4, edit_a, 0.0)])

    variables = [kiwi.Variable(f"v{i}") for i in range(count)]
    constraints = []
    for terms, constant, relation, strength in rows:
        expression = kiwi.Expression([kiwi.Term(variables[i], c) for i, c in terms], constant)
        constraints.append(kiwi.Constraint(expression, ["==", "<=", ">="][relation], strength))
    solver = kiwi.Solver()
    active: set[int] = set()
    edits: dict[int, tuple[float, float]] = {}
    snapshots = []
    unique_count = 0
    for op, index, value in steps:
        if op == 0:
            solver.addConstraint(constraints[index])
            active.add(index)
        elif op == 1:
            solver.removeConstraint(constraints[index])
            active.remove(index)
        elif op == 2:
            solver.addEditVariable(variables[index], value)
            edits[index] = (value, 0.0)
        elif op == 3:
            solver.suggestValue(variables[index], value)
            edits[index] = (edits[index][0], value)
        else:
            solver.removeEditVariable(variables[index])
            del edits[index]
        solver.updateVariables()
        values = [v.value() for v in variables]
        hard = max((violation(rows[i], values) for i in sorted(active) if rows[i][3] == REQUIRED), default=0.0)
        objective = sum(rows[i][3] * violation(rows[i], values) for i in sorted(active) if rows[i][3] != REQUIRED)
        objective += sum(strength * abs(values[i] - target) for i, (strength, target) in sorted(edits.items()))
        if hard > 1.0e-7:
            raise AssertionError(f"Kiwi produced infeasible scenario {case_id}: {hard}")
        unique = bool(pins) and pins.issubset(active)
        unique_count += int(unique)
        # Kiwi uses pointer-ordered symbols: equivalent bases can produce tiny
        # last-bit changes across processes. Canonicalize only oracle results,
        # never input coefficients; keep error below the MoonBit tolerance.
        canonical_objective = float(format(objective, ".9g"))
        canonical_values = [float(format(v, ".12g")) for v in values] if unique else []
        snapshots.append((True, 0.0, canonical_objective, canonical_values))

    result = [f'///|\ntest "kiwi oracle {case_id:03d}" {{', f"  oracle_run({case_id}, {count}, ["]
    for terms, constant, relation, strength in rows:
        encoded_terms = ", ".join(f"({i}, {number(c)})" for i, c in terms)
        result.append(f"    {{ terms: [{encoded_terms}], constant: {number(constant)}, relation: {relation}, strength: {number(strength)} }},")
    result.append("  ], [")
    result.extend(f"    ({op}, {index}, {number(value)})," for op, index, value in steps)
    result.append("  ], [")
    for feasible, hard, objective, values in snapshots:
        result.append(f"    (true, {number(hard)}, {number(objective)}, [{', '.join(number(v) for v in values)}]),")
    result.extend(["  ])", "}", ""])
    return "\n".join(result), len(steps), unique_count


def generate() -> tuple[str, int, int]:
    chunks = [HELPERS]
    operations = unique = 0
    for case_id in range(SCENARIOS):
        text, count, unique_count = make_case(case_id)
        chunks.append(text)
        operations += count
        unique += unique_count
    chunks.insert(1, f"// Actual corpus: {SCENARIOS} scenarios; {operations} checked operation snapshots;\n// {unique} unique-solution snapshots; 7 manually specified Kiwi exception checks.\n\n")
    return "\n".join(chunks), operations, unique


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail on fixture drift; never modify checked-in fixtures")
    args = parser.parse_args()
    if kiwi.__version__ != "1.4.9":
        parser.error(f"kiwisolver==1.4.9 required, found {kiwi.__version__}")
    errors = verify_exact_errors()
    text, operations, unique = generate()
    # Canonical formatting prevents an ordinary `moon fmt` from causing drift.
    # The formatter never computes expected results; those come only from Kiwi.
    text = subprocess.run(["moonfmt", "-"], input=text, text=True, encoding="utf-8",
                          capture_output=True, check=True).stdout
    encoded = text.encode("utf-8")
    if args.check:
        with tempfile.TemporaryDirectory(prefix="mooncassowary-oracle-") as directory:
            temporary = Path(directory) / OUTPUT.name
            temporary.write_bytes(encoded)
            actual = OUTPUT.read_bytes() if OUTPUT.exists() else b""
            if actual != temporary.read_bytes():
                diff = difflib.unified_diff(actual.decode("utf-8").splitlines(), text.splitlines(), fromfile=str(OUTPUT), tofile="regenerated", n=2)
                print("\n".join(list(diff)[:60]), file=sys.stderr)
                print("Oracle fixture drift: regenerate explicitly and review the change.", file=sys.stderr)
                return 1
        action = "CHECK OK"
    else:
        OUTPUT.write_bytes(encoded)
        action = "GENERATED"
    print(f"{action}: Kiwi {kiwi.__version__}, seed={SEED}, scenarios={SCENARIOS}, operation_snapshots={operations}, unique_snapshots={unique}, exact_errors={errors}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
